---
title: 'R-Package WhaleInjuryCovariates <br><br> Covariates for assessing whale injuries'
author: "jim.carretta@noaa.gov"
date: "7/29/2021"
output: html_document
---
GitHub Repository: https:GitHub.com/JimCarretta/WhaleInjuryCovariates
<br>

<H3>Covariates:</H3> <br>

<H4><b>*anchored*</b></H4>
<p>Evidence a whale was anchored or immobilized by                                entangling material or gear.  Narrative mentions                                  inability to dive or swim or that whale is                                        immobilized. Includes references to a                                             heavily-weighted whale with multiple pots/traps                                   impeding normal movement.</p>

<H4><b>*calf.juv*</b></H4>
<p>Narrative includes reference to an injured calf or juvenile. Also includes narratives where injury involves the mother of a dependent calf.</p>

<H4><b>*constricting*</b></H4>
<p>Evidence of a constricting entanglement, including line cutting into whale, wrapped tightly around body or flippers.</p>

<H4><b>*decline*</b></H4>
<p>Narrative includes evidence of a health decline, such as the presence of cyamids, emaciation, discolored skin, deformities caused by a chronic entanglement or severe vessel strike incident.</p>

<H4><b>*extensive.severe*</b></H4>	
<p>Evidence of severe injury that can include amputation or necrosis of body parts due to a chronic entanglement or acute vessel strike injury.</p> 

<H4><b>*fluke.peduncle*</b></H4>
<p>Narrative includes reference of entanglement or vessel strike injury that involves the tail, flukes, or peduncle.</p>

<H4><b>*gear.free*</b></H4>	
<p>Evidence that the whale freed itself from the gear or entangling material. Typically involves a whale resighted at a later date than the initial entanglement observation.</p>

<H4><b>*head*</b></H4>	
<p>Narrative indicates that the head, mouth, or blowhole was involved in the entanglement or vessel strike injury.</p>

<H4><b>*healing*</b></H4>
<p>Narrative refers to healing or healed wounds.</p>

<H4><b>*laceration.deep*</b></H4>
<p>Narrative includes reference to deep laceration resulting from vessel strike or entanglement. May include reference to blubber or muscle layers.</p>

<H4><b>*laceration.shallow*</b></H4>
<p>Narrative includes reference to shallow or superficial lacerations.</p>

<H4><b>*pectoral*</b></H4>
<p>Narrative includes involvement of pectoral flipper or ‘fins’ in entanglement or vessel strike injury.</p>

<H4><b>*swim.dive*</b></H4>
<p>Evidence that the whale is swimming, feeding, or diving normally.</p>

<H4><b>*trailing*</b></H4>			
<p>Was the whale trailing gear or other entangling material?</p>

<H4><b>*vessel.fast*</b></H4>
<p>Narrative includes reference to vessel speeds < 10 kts.</p>

<H4><b>*vessel.large*</b></H4>
<p>Narrative includes reference to large vessels such as military vessels, ferries, container ships, or vessel >65 ft in length.</p>

<H4><b>*vessel.slow*</b></H4>
<p>Narrative includes reference to vessel speeds >= 10 kts.</p>

<H4><b>*vessel.small*</b></H4>
<p>Narrative includes reference to small vessels such as sailboats, recreational vessels, RHIB vessels, or vessel size < 65 ft in length or smaller than the whale, if this can be determined.</p>

<H4><b>*wraps.multi*</b></H4>
<p>Narrative includes reference to whale with  multiple wraps of line or gear around body or appendage.</p>

<H4><b>*wraps.no*</b></H4>
<p>Narrative includes reference to a whale without any wraps of line or gear around body or appendage.</p>
<p>

<br>

Code example below shows how injury case narratives are searched for words/phrases 
used to generate covariates. A single covariate example ('decline') is given. Code 
for generating all covariates is found in the file 'Large Whale Injury Covariates.R' 
in the R-Package 'WhaleInjuryCovariates'.
Package includes sample data.frame 'LargeWhaleData'.

```
# Download R-Package 'WhaleInjuryCovariates':

 devtools::install_github('JimCarretta/WhaleInjuryCovariates')

# Example code for covariate identification from injury narratives.
#  uses covariate 'decline' as example.
#   data.frame narrative field must be named 'Narrative' for use with WhaleInjuryCovariates().
#    use function 'grepl' to search for words/phrases in 'Narrative'.
#     code covariates numerically as 1/0, aligned with their TRUE/FALSE (=presence/absence) value.

# Evidence of a health decline? 
#  Search 'Narrative' for words/phrases associated with health declines.
    
    decline <- grepl(" abnormal|chronic|deteriorat|fair|
     compromise|scoliosis|deform|cyamid|lice|lethargic|
      lesion|discolor|diatom|poor cond|poor health|poor body|
       poor over|poor skin|rake|skin|slough|thin |emaciated|malnourish|
        underweight|starv|mobility", LargeWhaleData$Narrative, ignore.case=T)
    
    decline <- as.numeric(lapply(decline, as.numeric))
     decline
    
# Use WhaleInjuryCovariates() to append covariates to each row of 'LargeWhaleData' 
    
    head(LargeWhaleData)

    new.data.frame <- WhaleInjuryCovariates(LargeWhaleData)

    head(new.data.frame)
    
```

